### ISSUE TITLE
Community Module info button not legible in dark theme

### ISSUE THREAD

**Issue by marcelwgn** [microsoft/react-native-gallery#402] opened 2024-03-24 14:51 UTC
The button/text indicating a control is provided through a community module is hardly legible in dark theme:
![Screenshot of React Native Gallery where the top right button indicating the control being a community control is using light text on light background](https://github.com/microsoft/react-native-gallery/assets/16122379/e6a8c07f-0962-4f26-8781-fcf1c76af462)

**Comment by jonthysell** [comment] 2024-03-25 17:02
This appears to be a duplicate of #381.

**Closed by jonthysell** 2024-03-25 17:02 UTC
Labels: duplicate
