### ISSUE TITLE
Changing Theme to dark in app's Settings doesn't do anything

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-gallery#107] opened 2021-04-20 17:38 UTC
![image](https://user-images.githubusercontent.com/22989529/115440378-86abcc80-a1c4-11eb-9870-29194027b0c9.png)

**Comment by chiaramooney** [comment] 2021-04-22 16:27
Ah yes. Currently the "Theme Mode" setting only changes the theme of the code snippets on the component pages and not the theme of the app entirely. Expanding theme change to the full app is on the to-do list.

**Comment by chiaramooney** [comment] 2021-06-28 17:08
Duplicate of #17

**Closed by chiaramooney** 2021-06-28 17:08 UTC
Labels: enhancement
